apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-qpext-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-qpext-28
    app.kubernetes.io/part-of: kserve-qptext
  name: kserve-qpext-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-qpext-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-qpext-28
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-qptext/kserve-qpext-28@sha256:8f5d13b428f8004cc931e2665b7d61a5043b0739489f3170f5d86ba8ff7cc3aa
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
