apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-qpext-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-qptext/kserve-qpext-28@sha256:620fe1f77e1ad285c3467a219e40997cfd0c8949c053072484bf29d0985e24f8
        name: container-image
        resources: {}
status: {}
