apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-qptext
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-qptext/kserve-qptext@sha256:35d4dd2ce32b741cb13154dd560a49534208dfd143696c106d52a78cefd8c520
        name: container-image
        resources: {}
status: {}
