apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-qptext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-qptext
    app.kubernetes.io/part-of: kserve-qptext
  name: kserve-qptext
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-qptext
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-qptext
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-qptext/kserve-qptext@sha256:35d4dd2ce32b741cb13154dd560a49534208dfd143696c106d52a78cefd8c520
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
